# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c8d95aa005c0b2df042dc57a7ff8d13a4adff4c06e8e318bf1a9cd30aed13e8912a310af132205b5552cf87f48c67272d37296d70547195b0a50da789d67d2b

test:
  secret_key_base: d4b19a923a221778de4e312c2fefc22ac5cf8e4b4a36f1e80cbc853c3a7ee838478043da2ff2aa02faf748e6a9a296e383ea776cf051dece1c6ac222a9f23364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
